#!/usr/bin/env bash
fzf-regen-menu () {
    result=`ls \
        $SIMPLE_CONFIG/function/* \
        $SIMPLE_CONFIG/desks/* \
        | sed "s/.*desks\/\(.*\)\.sh/\1/" \
        | sed "s/.*function\/\(.*\)/\1/" `

    rm $SIMPLE_CONFIG/data/menu

    for item in $result;
    do
        echo $item >> $SIMPLE_CONFIG/data/menu
    done
}
