#!/usr/bin/env sh
# Load test command enhance
. $SIMPLE_CONFIG/lib/is.sh

load-function () {
if is dir $1; then
    for i in $1/*; do
        if is dir "$i"; then
            . $i/*
        else
            . $i
        fi
    done
else 
    . $1
fi 
}
