#!/usr/bin/env bash
#
#color: cyan magenta red lightgreen green black lightyellow
#       white

function set_bg_color () {
    #color_word="\[$(bgcolor $1)\]$color_word\[$(bgcolor end)\]"
    color_word="$(bgcolor $1)$color_word$(bgcolor end)"
}

function set_fg_color () {
    #color_word="\[$(fgcolor $1)\]$color_word\[$(fgcolor end)\]"
    color_word="$(fgcolor $1)$color_word$(fgcolor end)"
}


color_word="$USER"
set_fg_color yellow
USER=$color_word

DATE_FROM_FORMAT=`date "+%Y-%m-%d %k:%M %A"`
color_word="$DATE_FROM_FORMAT"
set_fg_color lightgreen
DATE=$color_word


if [ -n "$DESK_NAME" ]; then
    color_word=$DESK_NAME
    set_bg_color green
    set_fg_color black
    DESK_NAME=$color_word
    SHOW_ENV="[env:$DESK_NAME]-"
fi

color_word="\w"
set_bg_color white
set_fg_color black
COLOR_PATH=$color_word

export PS1="$USER : $DATE\n$SHOW_ENV[$COLOR_PATH] > "
