#!/usr/bin/env bash
USER=$(fgcolor yellow $USER)$(fgcolor end)

DATE_FROM_FORMAT=`date "+%Y-%m-%d %k:%M %A"`
DATE=$(fgcolor lightgreen "$DATE_FROM_FORMAT")$(fgcolor end)

FG_RED=$(fgcolor red)
FG_END=$(fgcolor end)


if [ -n "$DESK_NAME" ]; then
    SHOW_ENV="[env:$(bgcolor green)$(fgcolor black)$DESK_NAME$(fgcolor end)$(bgcolor end)]-"
fi

export PS1="$USER : $DATE\n$SHOW_ENV[$FG_RED\w$FG_END] > "
