#!/usr/bin/env bash
#
#color: cyan magenta red lightgreen green black lightyellow
#       white
. $SIMPLE_CONFIG/lib/shml-1.1.0/shml.sh

function set_bg_color () {
    color_word="\[$(bgcolor $1)\]$color_word\[$(bgcolor end)\]"
}

function set_fg_color () {
    color_word="\[$(fgcolor $1)\]$color_word\[$(fgcolor end)\]"
}

less_color () {
#     termcap terminfo
# mb      blink     start blink
# md      bold      start bold
# me      sgr0      turn off bold, blink and underline
# so      smso      start standout (reverse video)
# se      rmso      stop standout
# us      smul      start underline
# ue      rmul      stop underline

export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_mb=$'\e[2m\e[38;5;180m'
export LESS_TERMCAP_md=$'\e[1m\e[38;5;200m'
export LESS_TERMCAP_so=$'\e[38;5;70m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[4m\e[38;5;31m'
export LESS_TERMCAP_ue=$'\e[0m'
}


color_word="$USER"
set_fg_color black
set_bg_color white
FORMATED_USER=$color_word


if [ -n "$DESK_NAME" ]; then
    color_word=$DESK_NAME
    set_bg_color green
    set_fg_color black
    PROMPT_DESK_NAME=$color_word
    SHOW_ENV="[env:$PROMPT_DESK_NAME]-"
fi

color_word="\w"
set_bg_color white
set_fg_color black
COLOR_PATH=$color_word

export PS1="$FORMATED_USER : [$COLOR_PATH]\n$SHOW_ENV> "

less_color
