#!/usr/bin/env bash
ecd () {
    run_ecd () {
        echo -ne `pwd`
        result="`ls -al | sed 1d | fzf --header 'Press esc, or select . to exit program'\
            | awk '{print $NF}'`"
        if [ "$result" = "." ]; then
            result=""
        fi
    }

    if [ ! -z "$1" ]; then
        cd $1
    else
        run_ecd

        while [ ! -z "$result" ]; do
            cd $result
            run_ecd
        done;
    fi
}
