#!/usr/bin/env bash
fzf-regen-menu () {
    result=`ls \
        $SIMPLE_CONFIG/function/public/* \
        $SIMPLE_CONFIG/desks/* \
        | sed "s/.*desks\/\(.*\)\.sh/\1/" \
        | sed "s/.*function\/public\/\(.*\)/\1/" `

    rm $SIMPLE_CONFIG/data/menu

    for item in $result;
    do
        echo $item >> $SIMPLE_CONFIG/data/menu
    done
    sort -o $SIMPLE_CONFIG/data/menu $SIMPLE_CONFIG/data/menu
}
